# Generated by Django 4.2.3 on 2023-08-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_date_created_product_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Date_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Date_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Stock',
            new_name='stock',
        ),
    ]
