# Generated by Django 4.2.2 on 2023-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='View_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('customer_id', models.PositiveIntegerField()),
            ],
        ),
    ]
